mode = "dark"

accent = "#6e8fb2"
selection = "#292b3b"
muted = "#7d8291"

background = "#1e2030"
dark_background = "#14151f"
darker_background = "#0f1018"
lighter_background = "#292b3b"

foreground = "#cdd3e1"
dark_foreground = "#7d8291"
light_foreground = "#d6e7ff"
bright_foreground = "#e8f1ff"

red = "#c98a9b"
yellow = "#c2b38d"
orange = "#c49a7a"
green = "#8eaf9d"
cyan = "#91b7bd"
blue = "#6e8fb2"
magenta = "#9b8fac"
brown = "#8f7668"

bright_red = "#d9a0ae"
bright_yellow = "#d2c49e"
bright_green = "#a0c0ae"
bright_cyan = "#a5cbd0"
bright_blue = "#a8b7d1"
bright_magenta = "#b2a3c2"
